# Generated by Django 4.2.6 on 2023-12-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_checkout_alter_cart_product_id_alter_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='city',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='fname',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='checkout',
            name='lname',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='postcode',
            field=models.IntegerField(default=0),
        ),
    ]
