# Generated by Django 4.2.6 on 2023-11-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ONLINEAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
